// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDe-YSeCBQFnsK_EPVhh8kVVQ1RTvoqGY',
    appId: '1:822422599703:web:5c0ddcbee46fd678548452',
    messagingSenderId: '822422599703',
    projectId: 'technomart-eef6a',
    authDomain: 'technomart-eef6a.firebaseapp.com',
    storageBucket: 'technomart-eef6a.firebasestorage.app',
    measurementId: 'G-ZP41XERQYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5iyxTCkrQFT_FhAiGPUFlbY1qHS4g1g',
    appId: '1:822422599703:android:e6aeed01e5c61aaa548452',
    messagingSenderId: '822422599703',
    projectId: 'technomart-eef6a',
    storageBucket: 'technomart-eef6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPYKaJNqChGVD7XeI4DueS_1QGhh7ypVE',
    appId: '1:822422599703:ios:dd1d987e382ec1f0548452',
    messagingSenderId: '822422599703',
    projectId: 'technomart-eef6a',
    storageBucket: 'technomart-eef6a.firebasestorage.app',
    iosBundleId: 'com.example.technomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPYKaJNqChGVD7XeI4DueS_1QGhh7ypVE',
    appId: '1:822422599703:ios:dd1d987e382ec1f0548452',
    messagingSenderId: '822422599703',
    projectId: 'technomart-eef6a',
    storageBucket: 'technomart-eef6a.firebasestorage.app',
    iosBundleId: 'com.example.technomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDe-YSeCBQFnsK_EPVhh8kVVQ1RTvoqGY',
    appId: '1:822422599703:web:82c510ecefa37bbe548452',
    messagingSenderId: '822422599703',
    projectId: 'technomart-eef6a',
    authDomain: 'technomart-eef6a.firebaseapp.com',
    storageBucket: 'technomart-eef6a.firebasestorage.app',
    measurementId: 'G-0NVZ2N21ZW',
  );
}
